### ISSUE TITLE
Dim/Red Only Display

### ISSUE THREAD

**Issue by DJBenson** [jnthas/mariobros-clock#3]
Hi

I've received my kit from Makerfabs today, flashed the firmware and connected to wifi. The unit appears to be working but the only colour displayed is red and the display is very dim.

Have I missed part of the hardware install as there were no instructions in the box? I've conencted the ESP32 to the port on the left of the unit (as seen from the rear), connected the spade connectors to the ESP32 and using one of the two-headed cables provided.

EDIT: I've just disconnected the 5V lead from the ESP32 to the top of panel 1 and the panel stayed on so not even sure the ESP32 is providing aux power to the panel (if it needs to).

**Comment by DJBenson** [comment]
It seems my 64x64 panel is different to ones in the instructions - not sure how I ended up with the wrong panel as I ordered as a kit from Makerfabs.

Anyway it seems I have a HUB75E panel so I need to recompile the firmware and specify an E_PIN value?

**Comment by jnthas** [comment]
Hi DJBenson. Great to hear you bought the kit. By your description, it seems you didn't connect the power supply. When display is only powered by USB, it looks like you said, very dim and all red. Please connect a 5v with 2 or 3 amps.

**Comment by DJBenson** [comment]
> Hi DJBenson. Great to hear you bought the kit. By your description, it seems you didn't connect the power supply. When display is only powered by USB, it looks like you said, very dim and all red. Please connect a 5v with 2 or 3 amps.

Slightly embarassed by this. Spent a good few hours Googling, compiling new code etc. and only making things worse, and just when I was about to throw in the towel I found reference to the diode bypass jumper 😄 

Thanks and apologies.
